### ISSUE TITLE
Can't select wake word

### ISSUE THREAD

**Issue by t3rr0rz0n3** [RASPIAUDIO/esphomeLuxe#3]
Hi,

I can't select the Wake Word option on my device; it appears to be disabled, even though it works fine on other devices. Is there anything I can check?

![Image](https://github.com/user-attachments/assets/3b212123-ef34-4610-aaed-11f053a4ccd5)

**Comment by RASPIAUDIO** [comment]
it's because it is now using wake word on device (which is better) so the default wake word is "Hey Jarvis" but others can be selected by editing the yaml

**Comment by t3rr0rz0n3** [comment]
Hi @RASPIAUDIO 

I've seen that it works sometimes when I say "ok nabu" but it's very random. Can the wake word be modified from the code?

**Comment by RASPIAUDIO** [comment]
select the keyword in the yaml right now it should react with hey_jarvis https://github.com/RASPIAUDIO/esphomeLuxe/blob/main/luxe_microWW.yaml

```
`micro_wake_word:
  id: mww
  models:
#    - model: okay_nabu
#      id: okat_nabu
    - model: hey_jarvis
#      id: hey_jarvis
#    - model: hey_mycroft
#      id: hey_mycroft
#    - model: alexa
#      id: alexa  
  vad:
  microphone: luxe_mic
  on_wake_word_detected:        
    - voice_assistant.start:
        wake_word: !lambda return wake_word;       

```
`
