### ISSUE TITLE
Device regularly resets with loud noise

### ISSUE THREAD

**Issue by Fabio72** [RASPIAUDIO/esphomeLuxe#7]
I used the Muse with HomeAssistant as media player, since 2023 with no updates.
It was working okayish (sometimes it needed reboot, recently it started loop playing announces).

I just updated with latest version and now it is unusable.
It plays fine but, randomly, it reboots with a loud noise at max volume and the startup chime.

It happened several times at night, waking up the whole family.

```
[D][sensor:093]: 'Battery voltage': Sending state 4.51100 V with 2 decimals of accuracy
[D][sensor:093]: 'Battery': Sending state 96.96455 % with 0 decimals of accuracy
[D][esp-idf:000][wifi]: W (351237) wifi:
[D][esp-idf:000][wifi]: [ADDBA]rx delba, code:39, delete tid:0
[D][esp-idf:000][wifi]: 

[D][esp-idf:000]: W (351271) httpd_txrx: httpd_sock_err: error in send : 128
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400ee9e9  PS      : 0x00060230  A0      : 0x800eea07  A1      : 0x3ffc06f0  
A2      : 0x204412cd  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0xb33fffff  A7      : 0xb33fffff  A8      : 0x800ee9e7  A9      : 0x3ffc06b0  
A10     : 0x00000000  A11     : 0x00060023  A12     : 0x8008986e  A13     : 0x3ffb1e30  
A14     : 0x3ffb4ac0  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000004  LBEG    : 0x400849d9  LEND    : 0x400849e1  LCOUNT  : 0x00000027  


Backtrace: 0x400ee9e6:0x3ffc06f0 0x400eea04:0x3ffc0710 0x400ec79f:0x3ffc0730 0x400ec7d6:0x3ffc0780 0x401c39ed:0x3ffc07a0 0x401c3aa5:0x3ffc07c0 0x400f1fe5:0x3ffc07e0 0x400f56a6:0x3ffc0810 0x400db7c2:0x3ffc0830




ELF file SHA256: 3b8baf6f805e5ab4

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7112
load:0x40078000,len:15624
load:0x40080400,len:4
load:0x40080404,len:3876
entry 0x4008064c
I (29) boot: ESP-IDF 5.1.5 2nd stage bootloader
```

**Comment by Fabio72** [comment]
```
[D][ring_buffer:034][ann_read]: Created ring buffer with size 1000000
[D][speaker_media_player.pipeline:114]: Reading FLAC file type
[D][micro_wake_word:19Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400ee586  PS      : 0x00060c30  A0      : 0x800ee61c  A1      : 0x3ffc0550  
A2      : 0x00b83fc0  A3      : 0x00000000  A4      : 0x00b83fc0  A5      : 0x00b83fc0  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0xfffffffe  A9      : 0x3ffc0500  
A10     : 0x00000000  A11     : 0x0000003c  A12     : 0x3ffc03e4  A13     : 0x00000000  
A14     : 0x3ffc03b4  A15     : 0x3ffc04d0  SAR     : 0x00000008  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00b83fc0  LBEG    : 0x4008a8c6  LEND    : 0x4008a8d1  LCOUNT  : 0x00000000  


Backtrace: 0x400ee583:0x3ffc0550 0x400ee619:0x3ffc0570 0x400ee65a:0x3ffc0590 0x400ee781:0x3ffc05e0 0x400eb52e:0x3ffc0600 0x400e392d:0x3ffc0620 0x400e3cf1:0x3ffc0650 0x400f3f2d:0x3ffc0670 0x400f3f5e:0x3ffc06a0 0x400e4d1a:0x3ffc0700 0x400e5647:0x3ffc0720 0x401c39ed:0x3ffc07a0 0x401c3aa5:0x3ffc07c0 0x400f1fe5:0x3ffc07e0 0x400f56a6:0x3ffc0810 0x400db7c2:0x3ffc0830




ELF file SHA256: 3b8baf6f805e5ab4

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7112
load:0x40078000,len:15624
load:0x40080400,len:4
load:0x40080404,len:3876
entry 0x4008064c
I (29) boot: ESP-IDF 5.1.5 2nd stage bootloader
```

**Comment by MacrosorcH** [comment]
I have a Muse Luxe used as media player for Music Assistant which worked ok-ish until ESPHome 2025.4.2, but the newer 2025.5.0 and 2025.5.1 made it unusable: MP3 playback stutters all the time. I even tried switching from arduino framework to esp-idf, and that's even worse because with esp-idf pause action doesn't work. TTS on Arduino still repeats forever. Radio playback is the only thing that works well. I have not seen the device reboot by itself though. But I have to admit that ESPHome support for Muse Luxe got a lot worse lately.

**Comment by Fabio72** [comment]
I wish I could go back to the previous version. Now I have to keep it down, at least at night.

**Comment by MacrosorcH** [comment]
@Fabio72 You can use this addon to install an old version of ESPHome: https://github.com/khenderick/esphome-legacy-addons

**Comment by Fabio72** [comment]
```
[D][sensor:093]: 'Battery voltage': Sending state 4.54715 V with 2 decimals of accuracy
[D][sensor:093]: 'Battery': Sending state 100.00000 % with 0 decimals of accuracy
[D][esp-idf:000][wifi]: W (4972721) wifi:
[D][esp-idf:000][wifi]: [ADDBA]rx delba, code:39, delete tid:0
[D][esp-idf:000][wifi]: 

[D][esp-idf:000]: W (4978543) httpd_txrx: httpd_sock_err: error in send : 128

E (4983523) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (4983523) task_wdt:  - loopTask (CPU 1)
E (4983523) task_wdt: Tasks currently running:
E (4983523) task_wdt: CPU 0: IDLE0
E (4983523) task_wdt: CPU 1: loopTask
E (4983523) task_wdt: Aborting.
E (4983523) task_wdt: Print CPU 1 backtrace




Backtrace: 0x401c87db:0x3ffc04d0 0x401a209d:0x3ffc04f0 0x400ee789:0x3ffc0510 0x400eb52e:0x3ffc0530 0x400e392d:0x3ffc0550 0x400e3cf1:0x3ffc0580 0x400f3f8a:0x3ffc05a0 0x401ccddd:0x3ffc05e0 0x400926a5:0x3ffc0610 0x4013687d:0x3ffc0660 0x40136e76:0x3ffc0690 0x40136ec3:0x3ffc06b0 0x400ee635:0x3ffc06d0 0x400ee9de:0x3ffc06f0 0x400eea04:0x3ffc0710 0x400ec79f:0x3ffc0730 0x400ec7d6:0x3ffc0780 0x401c39ed:0x3ffc07a0 0x401c3aa5:0x3ffc07c0 0x400f1fe5:0x3ffc07e0 0x400f56a6:0x3ffc0810 0x400db7c2:0x3ffc0830




ELF file SHA256: 3b8baf6f805e5ab4

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7112
load:0x40078000,len:15624
load:0x40080400,len:4
load:0x40080404,len:3876
entry 0x4008064c
I (29) boot: ESP-IDF 5.1.5 2nd stage bootloader
I (29) boot: compile time Apr 29 2025 12:12:36
```

**Comment by Fabio72** [comment]
> [@Fabio72](https://github.com/Fabio72) You can use this addon to install an old version of ESPHome: https://github.com/khenderick/esphome-legacy-addons

ESPHome is running in docker. I'm missing older yaml files for the muse

**Comment by eigenphase** [comment]
Did you ever figure out more? 
I have the same issue and my family hates the device (and me for the horrifying random loud noises)

**Comment by eigenphase** [comment]
I stripped down to the minimum YAML:

```
api:
  encryption:
    key: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.222.11
    gateway: 192.168.222.254
    subnet: 255.255.255.0

substitutions:
  name: "muse-luxe-01"
  friendly_name: "Muse Luxe Diningrm"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.2.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi

external_components:
    - source: github://RASPIAUDIO/esphomeLuxe@main
      components: [es8388]

esp32:
  board: esp-wrover-kit  
  flash_size: 4MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
  partitions: partitions_huge_luxe.csv

logger:
  level: VERY_VERBOSE

es8388:
  id: my_es8388

psram:
  mode: quad
  speed: 80MHz

i2c:
  sda: GPIO18
  scl: GPIO23

output:
  - platform: gpio
    id: dac_mute
    pin:
      number: GPIO21
      inverted: true
      mode:
        output: true

i2s_audio:
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5
    i2s_mclk_pin: GPIO0

speaker:
  - platform: i2s_audio
    id: luxe_speaker
    i2s_dout_pin: GPIO26
    dac_type: external
    sample_rate: 48000
    bits_per_sample: 16bit
    channel: stereo
    buffer_duration: 100ms

media_player:
  - platform: speaker
    name: None
    id: luxe_media_player
    announcement_pipeline:
      speaker: luxe_speaker
      format: FLAC
      sample_rate: 48000
      num_channels: 2   
```

And every 5-10th time playing an audio it crashes, reboots with loud noise and this is my debug capture:

```
[...]
[09:36:46][D][media_player:083]: 'Muse Luxe Diningrm' - Setting
[09:36:46][D][media_player:090]:   Media URL: http://10.227.4.10:8123/api/esphome/ffmpeg_proxy/81a00ce8150deb210d8888600f02ccf4/hz0nqw8_kxkxgNJAqniwSQ.flac
[09:36:46][D][speaker_media_player:406]: State changed to ANNOUNCING
[09:36:46][VV][app:460]: logger loop enabled from ISR
[09:36:46][D][speaker_media_player.pipeline:114]: Reading FLAC file type
[09:36:46][D][ring_buffer:034][ann_read]: Created ring buffer with size 1000000
[09:36:46][VV][component:223]: logger loop disabled
[09:36:46][VV][api.service:012]: send_message media_player_state_response: MediaPlayerStateResponse {
[09:36:46][VV][api.service:012]:  key: 4136933333
[09:36:46][VV][api.service:012]:  state: MEDIA_PLAYER_STATE_PLAYING
[09:36:46][VV][api.service:012]:  volume: 0.15
[09:36:46][VV][api.service:012]:  muted: NO
[09:36:46][VV][api.service:012]: }
[09:36:47][D][speaker_media_player.pipeline:124]: Decoded audio has 2 channels, 48000 Hz sample rate, and 16 bits per sample
[09:36:47][VV][app:460]: logger loop enabled from ISR
[09:36:47][D][i2s_audio.speaker:102]: Starting
[09:36:47][D][i2s_audio.speaker:106]: Started
[09:36:47][D][ring_buffer:034][speaker_task]: Created ring buffer with size 19200
[09:36:47][VV][component:223]: logger loop disabled
[09:36:48]Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.
[09:36:48]
[09:36:48]Core  0 register dump:
[09:36:48]PC      : 0x400920a2  PS      : 0x00060f33  A0      : 0x80091db1  A1      : 0x3ffd52e0  
[09:36:48]A2      : 0x3f800014  A3      : 0x3f80a258  A4      : 0x00060320  A5      : 0x3f4a244c  
[09:36:48]A6      : 0x00000039  A7      : 0x3f80a250  A8      : 0x00000000  A9      : 0x00790000  
[09:36:48]A10     : 0x3f80ad94  A11     : 0x3f80a254  A12     : 0x00000000  A13     : 0x00790000  
[09:36:48]A14     : 0x3ffb52f4  A15     : 0x0000cdcd  SAR     : 0x0000000a  EXCCAUSE: 0x0000001d  
[09:36:48]EXCVADDR: 0x0079000c  LBEG    : 0x40089e78  LEND    : 0x40089e94  LCOUNT  : 0xffffffff  
[09:36:48]
[09:36:48]
[09:36:48]Backtrace: 0x4009209f:0x3ffd52e0 0x40091dae:0x3ffd5300 0x40084687:0x3ffd5320 0x40094535:0x3ffd5340 0x400d8719:0x3ffd5360 0x400d873b:0x3ffd5380 0x400db07b:0x3ffd53a0
[09:36:48]
[09:36:48]
[09:36:48]
[09:36:48]
[09:36:48]ELF file SHA256: 2fb9f1cc4
[09:36:48]
[09:36:48]Rebooting...
```
